### ISSUE TITLE
Setting the HEX value resets the alpha channel

### ISSUE THREAD

**Issue by fabgallo** [zefoy/ngx-color-picker#134]
When typing/pasting an HEX value in the field when an alpha value was already present, the alpha value gets reset to 100%.

I am able to reproduce this in the [StackBlitz demo](https://stackblitz.com/github/zefoy/ngx-color-picker/tree/master/example?file=src%2Fapp%2Fapp.component.html) by replacing the color-picker at line 10 with
```
<input [style.background]="color1" [(colorPicker)]="color1"
       [cpAlphaChannel]="'enabled'" [cpOutputFormat]="'rgba'" />
```

Can you please let me know if this is an intended behaviour (after all, I am putting a #RRGGBB value without alpha) and if there are any plans of fixing it/supporting maintaining the alpha?

**Comment by sconix** [comment]
If you use a value that does not have alpha of course the alpha will be set to 1. So yes its intended and I am slightly struggling to believe that there would be a user that would expect it to work like that. Since user expect that the color picker shows the value that user inputs and if value does not have alpha it would be pretty strange to get / keep transparency. It would be a fairly easy to add such an option to keep it, but I would need to be convinced that it would be good option usability wise. I don't see point in adding features that are not usable.

**Comment by fabgallo** [comment]
Thank you for the quick reply!
I asked because we received feedback from one of our users who classified that behaviour as a bug.
In a condition similar to what I presented in the first post, the user would:

- open the color picker

![image](https://user-images.githubusercontent.com/2903427/44171914-8ff64a00-a0a9-11e8-90a4-e1d6b731cf01.png)

- change the alpha value (in the RGBA view, for example)

![image](https://user-images.githubusercontent.com/2903427/44171957-ae5c4580-a0a9-11e8-9dd9-68ea018f0fc5.png)

- cycle until they reach the HEX view

![image](https://user-images.githubusercontent.com/2903427/44172002-d77cd600-a0a9-11e8-9a57-44fffa88e022.png)

- then change the value (e.g. from #2889e**9** to #2889e**8**)

![image](https://user-images.githubusercontent.com/2903427/44172051-ff6c3980-a0a9-11e8-8703-d16a69b78cb7.png)

From the user's point of view, he is just changing the colour value and therefore the expectation is that the alpha value would no change, since this view doesn't have a separate input to deal with it (except for the slider).

**Comment by fabgallo** [comment]
I apologize, I should have mentioned we tried to use `cpAlphaChannel='always'` already. As you may guess, the issue with the users is that an Hex with 8 digits is not something they are used to: they would be expecting the alpha input to be separated from the colour input (and not in hex format)

**Comment by sconix** [comment]
Ok, I have to think about this bit and I will make a query to our usability person and if they think it should behave like you are suggesting then I will change this / or add a new mode. If they think the current way is better then somebody needs to make a PR to get such a functionality. I will comment here next week that what road we are taking (if I forget to reply next week then please feel free to ping me).

**Comment by fabgallo** [comment]
That is great. Thanks again :-)

**Comment by sconix** [comment]
I discussed with out design and UX team and they also thought that the transparency should reset to 1 when HEX code is written. The main point being that it could cause confusion if user does not notice the transparency and writes a HEX code but the color does not look at all like it should due to the transparency. We also checked couple of other tools that we use and they worked with the same logic. So it seems that its more common to reset the transparency than keep it. 

So until we get a bug report from users about this we are happy with how this works currently so I won't be adding this feature at least in the near future. Of course if somebody wants to make PR that adds another alpha mode that behaves like this I am glad to merge it.

**Comment by fabgallo** [comment]
Thanks for your reply and for discussing this issue with your team.
I will let my users know and, if they agree, we can try to create a PR for it (maybe the alpha mode could be `cpAlphaChannel='forced'` ?).

Thanks again for this amazing component.

**Comment by stephengardner** [comment]
I'm having this issue:
Hex8 is not supported in all mobile phones.
https://caniuse.com/#feat=css-rrggbbaa

I have users who need to copy/paste hex values, so I have HEX as default.

I want people to use rgba if desired, but they can never use RGBA when HEX is default and Alpha is not set to "Always"

Again - if Alpha is set to Always, then the colors don't work on some mobile phones.


Hex8 should be able to be disabled, while also allowing rgba.

I don't want users accidentally using Hex8, because again, it's not fully supported.

**Comment by sconix** [comment]
You can define the output format to be always rgba and not allow hex there. So you don't need to use the value user inputs.

**Comment by stephengardner** [comment]
I know that I can use rgba - actually I did that before and it worked well.
My issue is that I have users who are copy/pasting hex values from one service over to mine, and having HEX as the default is the desired output.  Often users don't even see that they can switch from RGBA to HEX.  

So having HEX as default and also having the Alpha channel, without defaulting to HEX8 is impossible?

**Comment by sconix** [comment]
I guess there could be cpDefaultInput that could be used to tell what should be the default input format shown. But this is completely different from this issue, so if you think such option should exist make a new issue about it. This is something that we might want as well and makes sense usability wise so there is a good change that I would add that.

**Comment by stephengardner** [comment]
Awesome - will do

**Comment by fabgallo** [comment]
@sconix please take a look at #138 when you get the chance

**Comment by sconix** [comment]
This will be now possible with the latest version that I will release shortly.
