### ISSUE TITLE
[Bug]: Uncaught (in promise): TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by mlakhara** [zefoy/ngx-color-picker#15]
When using the directive within  a component which is a custom form control value accessor, the directive throws this error:

`Uncaught (in promise): TypeError: Cannot read property 'toLowerCase' of null`

This is because during initialization of the directive (in ngOnInit) the value this.colorPicker is not set (is null). Since this occurs in angular change detection, it messes the whole change detection cycle for other components and they behave in a random manner.

**Comment by sconix** [comment]
Thanks, I will merge that for next version which I will release later this week.

**Comment by mlakhara** [comment]
Also, during ngOnInit of the ColorPicker Component this.colorPicker is set to null, even when the actual model that is bound has some value. This is restricting the use of this component as a custom form control.
If you wish, we can create another issue for this and work on the same to make this component more form friendly (using angular form's value accessor API)

**Comment by sconix** [comment]
Sure, all help is welcome. I plan to do small cleanup/re-write as soon as I have time since the code base is still from angular2-color-picker, but since that project really seems to be dead I plan to continue maintaining this and take this bit further as soon as I have the extra time. So in the meantime all fixes and improvements are naturally welcome.
