### ISSUE TITLE
Color picker dialog cannot be close in ios mobile device

### ISSUE THREAD

**Issue by frendable** [zefoy/ngx-color-picker#158]
Color picker dialog cannot be close in ios mobile device, must click another html input element to close the dialog. This is only happened in ios mobile device chrome browser

**Comment by sconix** [comment]
So it seems. Not sure what I can do since it seems that iOS safari won't unfocus input when clicking on a body. I have to study if there is a way to handle this is in the library, but for now you can always add an event handler to body to unfocus active element when tapped and that will close the dialog.

**Comment by Vojislav-Vukovic** [comment]
Just add` [cpCancelButton]="true" [cpOKButton]="true"` On this way user can also close the dialog if there is issue with some browser or devices
