### ISSUE TITLE
[cpOKButtonClass] doesn't work with component classes

### ISSUE THREAD

**Issue by Dmitry-TryBooking** [zefoy/ngx-color-picker#175]
My project doesn't have dependency on Bootstrap, so [cpOKButtonClass]= "'btn btn-primary btn-xs'" doesn't work. Adding locally defined classes doesn't work either, i.e.
[cpOKButtonClass]= "'my-class-for-ok-button'" where .my-class-for-ok-button is defined in the host component .scss file. Can replicate in StackBlitz at https://stackblitz.com/github/zefoy/ngx-color-picker/tree/master/example?file=src%2Fapp%2Fapp.component.html

Also, maybe it is a good idea to add direct styling capabilities as a safety net? Something like
[cpOKButton**Style**]= "'background-color: blue;'"

Thanks

**Comment by sconix** [comment]
You need to read how styling works in Angular. There is nothing that can be done in this library to overcome how Angular styling works.

**Comment by Dmitry-TryBooking** [comment]
Can you update your StackBlitz with example how to use local style instead of "'btn btn-primary btn-xs'"?
I agree that styling in Angular can be tricky.

**Comment by sconix** [comment]
I have tried to limit the readme and example to things specific for this library so that there is less for people to read so the library specific things are easier to spot. But I might add some example for styling next time I update. In the meanwhile there are plenty of info on the Internet how to style child / root components from component styles i.e. how to use deep selector (or some cases it might make even sense just to disable the style encapsulation). Its not even Angular specific thing, its used in other frameworks as well.

**Comment by Dmitry-TryBooking** [comment]
Ok, thank you! Will follow your references about deep selector.
