### ISSUE TITLE
Something like [cpCloseClickOutside]="false" for window resize

### ISSUE THREAD

**Issue by headscott** [zefoy/ngx-color-picker#194]
[cpCloseClickOutside]="false" works perfectly for its specific purpose. But the color picker still closes on window resize.

Is it possible to prevent closing generally? Or would you rather add a property like [cpCloseWindowResize] in the future?

**Comment by sconix** [comment]
Why is it a problem?

**Comment by devnull69** [comment]
I like this kind of answers ... a user asks in an issue for a solution that is "never a problem for a normal user"? What makes you think you know what a normal user of another user's app would be like?

Solution: Try to use `[cpDialogDisplay]="'inline'"` additionally. It should prevent closing upon window resize.

**Comment by headscott** [comment]
Thank you. That worked just great for my use case.

**Comment by sconix** [comment]
@devnull69 I do not know that's why I asked that why is this a problem. I.e. what would be such a use case since I can not think of any. Developers usually do not think at all what normal users need thats why 80% software is poorly usable and I try to not add features that encourage bad usability. Hence I always want to know the use case for adding features.
