### ISSUE TITLE
Successive setting to the value (colorPicker) externally fails to update the hue.

### ISSUE THREAD

**Issue by BBaysinger** [zefoy/ngx-color-picker#24]
Once you have set the picker's value, if you attempt to set it again externally it fails to update the hue. That is, the saturation, value, and alpha get updated, but not the hue. I commented out this line 184: 

`hsva.h = this.hsva.h;`

And now it works as expected. Hopefully. I haven't see any issues yet.

**Comment by sconix** [comment]
That is needed for the hue to stay at correct level when moving slider to the very left, I was bit afraid that the fix might bring problems with it since the code is not that well structured that I could easily limit when we need to keep the hue. I will find a proper fix and release a new version today. Thanks for reporting this!
