### ISSUE TITLE
Why using Math.min in ColorPickerService

### ISSUE THREAD

**Issue by mburger81** [zefoy/ngx-color-picker#31]
In the ColorPickerService are many helper methods, like 

```
rgbaToHsva(rgba: Rgba): Hsva {
        let r = Math.min(rgba.r, 1), g = Math.min(rgba.g, 1), b = Math.min(rgba.b, 1), a = Math.min(rgba.a, 1);
```

But I'm not sure, why do you use `Math.min`, this will always return `1` and so the converstion from `rgbaToHsva` would never work!! The same issue is on many other methods.

Can you help?

**Comment by mburger81** [comment]
Does it support only value from [0, 1] and not from [0, 255]?

**Comment by sconix** [comment]
The conversion works just fine, if you look at the code the color given for rgbaToHsva has the percentage value of the r/g/b levels not the value. I don't know why the code is made in a such way since this is not originally my code. It would be better to have conversion functions that take normal color string and not something that has been already preprocessed. 

I will be doing some code refactoring / cleanup during the summer and this is something that will change.
