### ISSUE TITLE
Ability to reset value

### ISSUE THREAD

**Issue by maxkorz** [zefoy/ngx-color-picker#50]
It would be nice to have an ability to clear the input (set it to `null`). Maybe it should be a button displayed next to "ok"/"cancel" buttons.

**Comment by sconix** [comment]
Not sure thats a function for the dialog. Would need to know your use case better to understand the need to have that action in the dialog.

**Comment by maxkorz** [comment]
@sconix I used this plugin for angular1 https://bgrins.github.io/spectrum/#toc25 as you can see, it has a clear button

My use-case is a configurable interface for my website. The settings page looks like this https://i.imgur.com/kECUSR9.png
User is able to select a custom color for header navbar. If color is not set (value is null), I display a default color.

**Comment by sconix** [comment]
UX vice I think the reset color action does not belong to the dialog, imho it should be next to the input field and not when selecting the color. If there are more who needs this then sure I can add such thing, but atm this kind of feature is not on top of the list.

**Comment by maxkorz** [comment]
@sconix would you accept a PR?

**Comment by sconix** [comment]
Sure. I am just still thinking that does it make sense UX vice to open the dialog to reset the color. In most cases it would make sense to have the reset to defaults action some where else such as next to the input where dialog is opened. But now when I think of it I guess there are some cases that it would make sense to have button to use default color inside the dialog. 

So could it be so that the input would be cpResetButton (+ Text and Class inputs like other buttons). And I guess when clicked it should use the cpFallbackColor so that there is no need to introduce more inputs.

**Comment by sconix** [comment]
I am also planning to make a bigger cleanup / rewrite for this library so that all the components are separated so that one could also easily make fully custom color dialog, but I don't have timeframe for this.
