### ISSUE TITLE
[Question] Why do you use the ignoreChanges property?

### ISSUE THREAD

**Issue by meiuqer** [zefoy/ngx-color-picker#52]
ColorPickerDirective.prototype.ngOnChanges = function (changes) {
             if (changes.colorPicker) {
                 if (this.dialog && !this.ignoreChanges) {
                     if (this.cpDialogDisplay === 'inline') {
                         this.dialog.setInitialColor(changes.colorPicker.currentValue);
                     }
                    this.dialog.setColorFromString(changes.colorPicker.currentValue, false);
                }
                this.ignoreChanges = false;
            }
        };

What would happen if i deleted the ingoreChanges check? Are you trying to prevent an infinite loop?

Thanks

**Comment by sconix** [comment]
I would say its there to prevent a loop or prevent given value to be effected by the internal color handling. Or it could just be unnecessary check altogether I haven't look into it more closely since I am planning to do a code cleanup in near future. The current code is not written by me and has few issues such as this.

**Comment by meiuqer** [comment]
I did a quick test, and nothing special came up. Ill probably do a more thorough test, if nothing comes up, ill probably delete it myself.

Thanks for the quick answer though. This can be closed. Maybe if you figure out what it is, give us a shout.
