### ISSUE TITLE
Using data in scss

### ISSUE THREAD

**Issue by dcbroad3** [zefoy/ngx-color-picker#75]
I'm looking into using a CSP with my website that includes a restriction on img-src. Currently, the reference to this project is preventing me from using that policy because the scss files in this project use data urls. Could we remove the data urls and use actual references to images instead? 

Something like this fork: https://github.com/dcbroad3/ngx-color-picker

**Comment by sconix** [comment]
Can't you just override the css yourself? Or will the existence of those data url even if not used cause a problem? I feel like this is so special case that making the library worse for 99% of the people is not the best way. So I can think if there is a way to have both ways, but I don't feel like making the only way to use images since it wont make sense for most people and will make loading the widget slower.

**Comment by dcbroad3** [comment]
I can override them myself, although I don't see a solution that doesn't require !important tags (since the styles are encapsulated), which is a minor nuisance. I still think it might be valuable to add this to ngx-color-picker as an option, but since I'm able to host the images myself to get around the issue it's not critical.

**Comment by sconix** [comment]
I will keep this in mind. The style encapsulation will be turned off for next release since I don't see it that useful for this type of component.
