### ISSUE TITLE
Cannot assign to a reference or variable!

### ISSUE THREAD

**Issue by ar53n** [zefoy/ngx-color-picker#83]
Hello I want to create some color-pickers from  array of colors

```
public arrayC: string[] = ['#f200bd', '#f200bd']
<div *ngFor="let color of arrayC">
                <input [(colorPicker)]="color" [style.background]="color" [value]="color" />
            </div>
```

But get error 
`compiler.js:26008 Uncaught Error: Cannot assign to a reference or variable`

**Comment by sconix** [comment]
Well thats not really related to this library. By looping with let color of arrayC you are assigning the array  values to the color variable which does not exist after the loop. So try ngFor="let color of arrayC; let i = index" and then assign the color from arrayC[i].

**Comment by ar53n** [comment]
@sconix I tried this way too, but there is an error 
`Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges`
 #63

**Comment by sconix** [comment]
You are destroying your view (i.e. color picker) before it has got change to emit the new value.

**Comment by sconix** [comment]
Actually the problem you have is that when ever the value change the ngFor re-creates the inputs so therefore the view gets destroyed while the change detection is being run. I will check at some point if I can prevent the error in this kind of situation, but anyway for proper use you should use trackBy for the ngFor to avoid not re-creating the elements all the time. I.e. use trackBy function that returns the index so the elements wont be re-created every time the value changes.

**Comment by ar53n** [comment]
@sconix I'm using a `trackBy`. But still this error occurs, but I see that in version 5, you deleted this piece of code?

**Comment by sconix** [comment]
By properly using trackBy the error will go away, I know since I quickly verified it :) The trackBy with the index will prevent the input element getting destroyed when the value changes so the view destroying can not happen and therefore error goes away.

And no there has not been anything deleted from version 5. When I have time (some day this week) I will check if I can modify the code so that the error does not occur in any situations, but as said anyway its bad code to keep destroying the color picker every time the value changes so the fix should be in the application side.

**Comment by ar53n** [comment]
@sconix OK thank you I'll check it again will check.  And will reproduce on plunker.
I am about this. Was deleted in 5 version Angular 
[Error in this line](https://github.com/zefoy/ngx-color-picker/commit/a3a3a7b360446defa1704e0a00cd72d756926033)

**Comment by sconix** [comment]
Ah but thats not causing the error, I did test the loop thing on latest 5.x version of this library and it still does happen if trackBy is not used.

**Comment by ar53n** [comment]
@sconix Thank you very much. It was my fail. I wrote `trackBy :  tackByFn` instead `trackByFn`

**Comment by sconix** [comment]
No worries it happens :) Anyway thanks for reporting this since this is a really simple way to reproduce the error so I can have a look that if this error could be avoided. Since even in this case its naturally much better to use trackBy to avoid the error, but there are situations with ngIf etc. that might get too complicated to handle without getting this error.
