### ISSUE TITLE
Disable hex input auto completing

### ISSUE THREAD

**Issue by tommy-ly** [zefoy/ngx-color-picker#84]
At the moment there is some behaviour where typing the first three characters into the hex input field will auto complete. 

Example:

I type in #b5d, the input control will change the value to #bb55dd. 

Can we add an option to disable this? I'm also noticing when deleting characters it will sometimes add extra characters changing the colour as I'm deleting them which may be linked to the behaviour described above.

**Comment by sconix** [comment]
Well its up to the developer how the output value is used. Color picker always outputs the color that it shows and if you connect the output directly to the input then it naturally changes the input value while you are typing. If you don't want that then you can use the other output like when dialog is closed or color is accepted to update the value of the input.

Having parameter for the output behavior does not make sense since the output always needs to match what is displayed in the color picker.

**Comment by tommy-ly** [comment]
I'm not sure we're talking about the same thing. I'm referring to the hex input box automatically completing my input for me but I don't want it to. 

Referring back to the example I used say I want to type in the value #b5dabc, currently the flow is:
1. Clear hex input box
2. Type in #b5d
3. At this point the hex input will automatically input #bb55dd.
4. I now need to keep deleting the characters until it's #b5d (while I'm deleting it also adds extra characters for some reason)
5. Enter abc.

I'm referring to having the auto completion of the hex value in step 3 as an option that can be toggled.

Apologies if it wasn't clear in the initial post.

**Comment by sconix** [comment]
Ah you don't mean the input that has the color picker directive. Now I understand, I would say this is a bug. I will fix it tomorrow and release a new version.

**Comment by tommy-ly** [comment]
Much appreciated!

**Comment by abisheksharma** [comment]
I am experiencing this same issue again. It's happening in both Chrome and Edge. Did we ever confirmed that this was fixed?

**Comment by mkmukesh892** [comment]
I am also experiencing the same issue in our Angular 12 project with two-ways databinding with ngx-color-picker version 10.0.1. However, it seems to be working fine in Angular 11. Has anyone encountered this before or found a solution?
