### ISSUE TITLE
Input allows more then 7 characters to be written

### ISSUE THREAD

**Issue by PodaruDragos** [zefoy/ngx-color-picker#85]
Is there any way of to have a validation to only write 7 characters when manually writing a hex code ?

**Comment by sconix** [comment]
Why would you need a such thing?

**Comment by PodaruDragos** [comment]
Because a normal hex code is 7 characters maximum and despite it's working properly it's not clear for some people apparently to be able to write more.

**Comment by sconix** [comment]
Yes but the hex value will always be replaced with the actual value parsed from the users input. So I don't see a reason for limiting what the user can type. If user types #000000000 it will be corrected to #000000 when the field is unfocused. And hex can be 9 characters as well so having complex validation rules and error message showing for something that most likely the user will understand when the value is corrected by the dialog seems bit excessive.

So I am not seeing the benefit of limiting what user can write if the end result is what the user wants I don't think it matters if user types exactly the correct value or not since the shown color is what user "accepts" not the value that he/she writes.

You can always do the validation yourself, just hookup to the inputChange output and if the value is not valid then you can set a new color value for the dialog.
